# Generated by Django 5.1.5 on 2025-01-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_review_options_remove_review_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('PHYS', 'Fizyka'), ('MATH', 'Matematyka')], max_length=4)),
                ('topic', models.CharField(max_length=100)),
                ('embed_code', models.TextField(help_text='Paste Google Slides embed iframe code here')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
